apiVersion: v1
kind: Secret
metadata:
  name: grape-psql-secrete
  namespace: demo
type: Opaque
stringData:
  GRAPE_PSQL_DATABSE: api_db
  GRAPE_PSQL_USERNAME: ""
  GRAPE_PSQL_PASSWORD: ""

  PGADMIN_EMAIL: ""
  PGADMIN_PASSWORD: ""