apiVersion: apps/v1
kind: Deployment
metadata:
  name: grape-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grape
  template:
    metadata:
      labels:
        app: grape
    spec:
      # serviceAccountName: api-sa
      containers:
        - name: grape
          image: grimreapermortis/grape:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31337
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grape-redis-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grape-redis
  template:
    metadata:
      labels:
        app: grape-redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          ports:
            - containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grape-psql-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grape-psql
  template:
    metadata:
      labels:
        app: grape-psql
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: grape-psql-pvc
      containers:
        - name: grape-psql
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
              readOnly: false
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: grape-psql-secrete
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grape-psql-secrete
                  key: DB_PASS

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: grape-psql-secrete
                  key: DB_NAME

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
