apiVersion: v1
kind: PersistentVolume
metadata:
  name: grape-psql-pv
  namespace: demo
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /media/sdb1/nfs/psql
    server: 192.168.10.1
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: grape-psql-pvc
    namespace: demo
