apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grape-config-pvc
  namespace: prod
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grape-psql-pvc
#   namespace: demo
# spec:
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 10Gi
