apiVersion: v1
kind: Service
metadata:
  name: grape-service
  namespace: demo
spec:
  selector:
    app: grape
  ports:
    - port: 31337
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: grape-redis-service
  namespace: demo
  labels:
    app: grape-redis
spec:
  selector:
    app: grape-redis
  ports:
    - port: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: grape-psql-service
  namespace: demo
  labels:
    app: grape-psql
spec:
  selector:
    app: grape-psql
  ports:
    - port: 5432
