server:
  address: localhost:31337
  prefix: /grape
  migrations: migrations/

psql:
  name: api_db
  host: localhost
  port: 7432
  username: root
  password: root
  logger: false

redis:
  db: 0
  address: localhost:6379
  username: ""
  password: ""

void:
  url: http://localhost:8003/void
  username: root
  password: root

jwt:
  access_secret: TEST
  refresh_secret: TEST
  access_expire: 30d
  refresh_expire: 30d
