server:
  address: 0.0.0.0:31337
  prefix: /grape
  migrations: migrations/

psql:
  name: api_db
  host: 172.17.0.1
  port: 7432
  username: root
  password: root
  logger: false
  options:
    health_timeout: 5s
    health_retries: 24

redis:
  db: 0
  address: 172.17.0.1:6379
  username: ""
  password: ""

void:
  url: http://172.17.0.1:8003/void
  username: root
  password: root

jwt:
  access_secret: TEST
  refresh_secret: TEST
  access_expire: 30d
  refresh_expire: 30d
