server:
  address: localhost:31337
  prefix: /grape
  migrations: migrations/

psql:
  name: api_db
  host: localhost
  port: 7432
  username: ""
  password: ""
  logger: true

redis:
  db: 0
  address: localhost:6379
  username: ""
  password: ""

void:
  url: http://192.168.0.106:8003/void
  username: ""
  password: ""

jwt:
  access_secret: ""
  refresh_secret: ""
  access_expire: 2h
  refresh_expire: 30d
