server:
  host: localhost
  port: 31337
  prefix: /grape
  migration: migrations/

psql:
  name: api_db
  host: localhost
  port: 7432
  user: root
  pass: root
  logger: false

redis:
  name: ""
  host: localhost
  port: 6379
  user: ""
  pass: ""

jwt:
  access_secret: HELLO
  refresh_secret: HELLO
  access_expire: 10m
  refresh_expire: 10m
