name: ci-test

on:
  push:
    branches: [master, dev]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      void:
        image: grimreapermortis/void:dev
        ports:
          - 8003:8003

      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: api_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 7432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install make
        run: sudo apt install -y make

      - name: Install swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build swagger
        run: make swagger

      - name: Create database file from template
        run: cp configs/database.template.yaml configs/database.yaml

      - name: Install packages
        run: go mod download

      - name: Run tests
        run: make test
