name: ci-test

on:
  push:
    branches: [master, dev]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      void:
        image: grimreapermortis/void:dev
        options: >-
          --health-cmd "curl -f http://localhost:8003/void"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8003:8003

      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: api_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 7432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install packages & build swagger
        run: |
          sudo apt install -y make
          go install github.com/swaggo/swag/cmd/swag@latest
          go mod download
          make swagger

      - name: Create config files from template
        run: |
          cp configs/database.template.yaml configs/database.yaml
          cp configs/config.template.yaml configs/config_test.yaml
          cp configs/config.template.yaml configs/config.yaml

      - name: Create Geolite temp file
        run: |
          touch migrations/tmp/GeoLite2-Country-Blocks.csv
          touch migrations/tmp/GeoLite2-Country-Locations-en.csv
          echo "network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider" >> migrations/tmp/GeoLite2-Country-Blocks.csv
          echo "geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union" >> migrations/tmp/GeoLite2-Country-Locations-en.csv
          echo "1.0.0.0/24,2077456,2077456,,0,0" >> migrations/tmp/GeoLite2-Country-Blocks.csv
          echo "49518,en,AF,Africa,RW,Rwanda,0" >> migrations/tmp/GeoLite2-Country-Locations-en.csv

      - name: Run tests
        run: make test
